backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

# Specify where the CMS should look for media content FIXME: the public folder may need a quickstart/ prefix too
media_folder: "quickstart/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "quickstart/content/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Last Edited Date", name: "lastmod", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Post Author",
             name: "authors",
             widget: "relation",
             collection: "author",
             searchFields: ["id", "author_name"],
             valueField: "author_name",
             displayFields: ["author_name"]}
      - {label: "Categories", name: "categories", widget: "list", allow_add: false, default: ["articles"]}
      - {label: "slug", name: "slug", widget: "string", default: ["{{slug}}"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}


